import { GameBQuestionDto } from '../../../models/session.model';

const BASE = 'assets/games/game-b/questions';

export const GAME_B_QUESTIONS: GameBQuestionDto[] = [
  {
    id: 'b-q1',
    mediaType: 'image',
    imageSrc: `${BASE}/q01/TGV-orange.png`,
    question: 'Quel est ce célèbre train rapide orange qui a révolutionné les voyages en France dès 1981 ?',
    source: 'Souvenir du quotidien',
    caption: 'Train grande vitesse',
    hint: 'Il reliait Paris à Lyon en moins de 3 heures et portait trois lettres.',
    choices: [
      { id: 'a', label: 'Le TGV', isCorrect: true },
      { id: 'b', label: 'Le Corail', isCorrect: false },
      { id: 'c', label: "L'Orient Express", isCorrect: false },
    ],
  },
  {
    id: 'b-q2',
    mediaType: 'image',
    imageSrc: `${BASE}/q02/Minitel.png`,
    question: 'Quel est le nom de ce petit terminal que France Télécom installait gratuitement chez les abonnés dans les années 80 ?',
    source: 'Souvenir du quotidien',
    caption: 'Terminal électronique',
    hint: "On l'utilisait pour consulter l'annuaire et commander des billets de train.",
    choices: [
      { id: 'a', label: 'Le Minitel', isCorrect: true },
      { id: 'b', label: 'Le Télétel', isCorrect: false },
      { id: 'c', label: "L'Antiope", isCorrect: false },
    ],
  },
  {
    id: 'b-q3',
    mediaType: 'image',
    imageSrc: `${BASE}/q03/Vintage_pro_Tv.png`,
    question: 'Comment appelait-on ce téléviseur avec ses grosses molettes de réglage et son antenne sur le dessus ?',
    source: 'Souvenir du quotidien',
    caption: 'Téléviseur vintage',
    hint: 'On réglait la luminosité et le contraste avec de grandes molettes sur le côté.',
    choices: [
      { id: 'a', label: 'Un téléviseur à tube cathodique', isCorrect: true },
      { id: 'b', label: 'Un magnétoscope', isCorrect: false },
      { id: 'c', label: 'Un rétroprojecteur', isCorrect: false },
    ],
  },
  {
    id: 'b-q4',
    mediaType: 'image',
    imageSrc: `${BASE}/q04/Plume.png`,
    question: 'Où versait-on l\'encre (souvent de marque Sergent-Major) pour écrire sur nos cahiers ?',
    source: 'Souvenir du quotidien',
    caption: 'Encre et plume',
    hint: "L'encre violette y était souvent versée par le maître.",
    choices: [
      { id: 'a', label: 'Dans un encrier encastré dans le bureau', isCorrect: true },
      { id: 'b', label: "Dans un tube de peinture à l'eau", isCorrect: false },
      { id: 'c', label: 'Dans un stylo à réservoir', isCorrect: false },
    ],
  },
  {
    id: 'b-q5',
    mediaType: 'audio',
    audioSrc: `${BASE}/q05/lhorloge-parlante.mp3`,
    question: 'Écoutez cet extrait. Quel était ce célèbre service téléphonique que l\'on appelait au 36 99 pour ne pas être en retard ?',
    source: 'Souvenir du quotidien',
    caption: 'Service téléphonique',
    hint: '"Au quatrième top, il sera exactement..."',
    choices: [
      { id: 'a', label: "L'horloge parlante", isCorrect: true },
      { id: 'b', label: 'Le réveil par téléphone', isCorrect: false },
      { id: 'c', label: 'Le répondeur de la Poste', isCorrect: false },
    ],
  },
  {
    id: 'b-q6',
    mediaType: 'image',
    imageSrc: `${BASE}/q06/Mange-disque.png`,
    question: 'Quel est le nom de cet appareil coloré, très populaire chez les jeunes dans les années 70 pour écouter des 45 tours ?',
    source: 'Souvenir du quotidien',
    caption: 'Lecteur de disques',
    hint: 'Son nom vient du fait qu\'il "avalait" le disque par une fente.',
    choices: [
      { id: 'a', label: 'Le Mange-disque', isCorrect: true },
      { id: 'b', label: 'Le Walkman (Baladeur)', isCorrect: false },
      { id: 'c', label: 'Le Jukebox portable', isCorrect: false },
    ],
  },
  {
    id: 'b-q7',
    mediaType: 'audio',
    audioSrc: `${BASE}/q07/Le-lund.mp3`,
    question: 'Écoutez cet extrait. Qui est ce célèbre chanteur, véritable idole des années 70, toujours accompagné de ses danseuses ?',
    source: 'Souvenir du quotidien',
    caption: 'Chanson des années 70',
    hint: 'On le surnommait affectueusement "Cloclo".',
    choices: [
      { id: 'a', label: 'Claude François', isCorrect: true },
      { id: 'b', label: 'Michel Polnareff', isCorrect: false },
      { id: 'c', label: 'Joe Dassin', isCorrect: false },
    ],
  },
  {
    id: 'b-q8',
    mediaType: 'image',
    imageSrc: `${BASE}/q08/portable-record-player.png`,
    question: 'Comment appelait-on ce tourne-disque portable en forme de valisette, souvent de marque Teppaz ?',
    source: 'Souvenir du quotidien',
    caption: 'Tourne-disque portable',
    hint: "C'était l'ancêtre de la chaîne hi-fi, qu'on emmenait dans les surprises-parties.",
    choices: [
      { id: 'a', label: 'Un électrophone portable', isCorrect: true },
      { id: 'b', label: 'Un gramophone à manivelle', isCorrect: false },
      { id: 'c', label: 'Un magnétophone à bandes', isCorrect: false },
    ],
  },
  {
    id: 'b-q9',
    mediaType: 'image',
    imageSrc: `${BASE}/q09/Socotel.png`,
    question: 'Comment composait-on un numéro avec ce téléphone emblématique des années 70, le modèle Socotel S63 ?',
    source: 'Souvenir du quotidien',
    caption: 'Téléphone à cadran',
    hint: 'Il fallait faire un mouvement circulaire puis relâcher.',
    choices: [
      { id: 'a', label: 'En tournant le cadran avec le doigt', isCorrect: true },
      { id: 'b', label: 'En appuyant sur de grosses touches', isCorrect: false },
      { id: 'c', label: 'En demandant à une opératrice', isCorrect: false },
    ],
  },
  {
    id: 'b-q10',
    mediaType: 'image',
    imageSrc: `${BASE}/q10/q10-scrabble.png`,
    question: 'Quel jeu de lettres passionnait les familles lors des longues soirées d\'hiver ?',
    source: 'Souvenir du quotidien',
    caption: 'Jeu de société',
    hint: 'Il fallait former des mots sur un plateau quadrillé pour marquer des points.',
    choices: [
      { id: 'a', label: 'Le Scrabble', isCorrect: true },
      { id: 'b', label: 'Le Boggle', isCorrect: false },
      { id: 'c', label: 'Le Rummikub', isCorrect: false },
    ],
  },
  {
    id: 'b-q11',
    mediaType: 'image',
    imageSrc: `${BASE}/q11/q11-appareil-photo.png`,
    question: 'Quel appareil permettait de capturer les moments précieux avant l\'ère numérique ?',
    source: 'Souvenir du quotidien',
    caption: 'Appareil photo argentique',
    hint: 'Il utilisait des pellicules 24 ou 36 poses qu\'il fallait faire développer.',
    choices: [
      { id: 'a', label: 'Un appareil photo argentique', isCorrect: true },
      { id: 'b', label: 'Un projecteur de diapositives', isCorrect: false },
      { id: 'c', label: 'Un caméscope VHS', isCorrect: false },
    ],
  },
  {
    id: 'b-q12',
    mediaType: 'image',
    imageSrc: `${BASE}/q12/q12-magnetophone.png`,
    question: 'Quel appareil permettait d\'enregistrer et de réécouter ses chansons préférées sur cassettes ?',
    source: 'Souvenir du quotidien',
    caption: 'Magnétophone à cassettes',
    hint: 'On devait rembobiner la cassette avec un crayon quand elle se déroulait.',
    choices: [
      { id: 'a', label: 'Un magnétophone', isCorrect: true },
      { id: 'b', label: 'Un lecteur de disques', isCorrect: false },
      { id: 'c', label: 'Un Walkman', isCorrect: false },
    ],
  },
  {
    id: 'b-q13',
    mediaType: 'audio',
    audioSrc: `${BASE}/q13/q13-radio-generique.mp3`,
    question: 'Écoutez cet extrait culte. Quel jeu radiophonique des années 80 réunissait les plus grands humoristes français ?',
    source: 'Souvenir du quotidien',
    caption: 'Jeu radiophonique',
    hint: 'C\'était le rendez-vous incontournable du samedi matin sur RTL.',
    choices: [
      { id: 'a', label: 'Les Grosses Têtes', isCorrect: true },
      { id: 'b', label: 'Qui Veut Gagner des Millions', isCorrect: false },
      { id: 'c', label: 'Le Jeu des 1000 Francs', isCorrect: false },
    ],
  },
  {
    id: 'b-q14',
    mediaType: 'image',
    imageSrc: `${BASE}/q14/q14-calculatrice.png`,
    question: 'Quel petit appareil révolutionnaire permettait de faire des calculs complexes en quelques secondes ?',
    source: 'Souvenir du quotidien',
    caption: 'Calculatrice de poche',
    hint: 'Elle fonctionnait avec des piles et affichait les résultats sur un petit écran.',
    choices: [
      { id: 'a', label: 'Une calculatrice de poche', isCorrect: true },
      { id: 'b', label: 'Une règle à calcul', isCorrect: false },
      { id: 'c', label: 'Un boulier', isCorrect: false },
    ],
  },
  {
    id: 'b-q15',
    mediaType: 'image',
    imageSrc: `${BASE}/q15/q15-montre.png`,
    question: 'Quel accessoire indispensable au poignet marquait le passage du temps dans la vie quotidienne ?',
    source: 'Souvenir du quotidien',
    caption: 'Montre mécanique',
    hint: 'Il fallait la remonter régulièrement pour qu\'elle continue de fonctionner.',
    choices: [
      { id: 'a', label: 'Une montre mécanique', isCorrect: true },
      { id: 'b', label: 'Un chronomètre', isCorrect: false },
      { id: 'c', label: 'Un minuteur de cuisine', isCorrect: false },
    ],
  },
  {
    id: 'b-q16',
    mediaType: 'image',
    imageSrc: `${BASE}/q16/q16-stylo-bic.png`,
    question: 'Quel stylo à bille bleu révolutionnaire était l\'outil d\'écriture par excellence à l\'école et au bureau ?',
    source: 'Souvenir du quotidien',
    caption: 'Stylo à bille',
    hint: 'Son prix très abordable l\'a rendu accessible à tous les écoliers.',
    choices: [
      { id: 'a', label: 'Le stylo Bic', isCorrect: true },
      { id: 'b', label: 'Le stylo Parker', isCorrect: false },
      { id: 'c', label: 'Le stylo Waterman', isCorrect: false },
    ],
  },
  {
    id: 'b-q17',
    mediaType: 'image',
    imageSrc: `${BASE}/q17/q17-lampe-bureau.png`,
    question: 'Quel objet éclairait les bureaux et les tables de nuit avec son design caractéristique des années 70 ?',
    source: 'Souvenir du quotidien',
    caption: 'Lampe de bureau',
    hint: 'Elle avait souvent un bras articulé et une base lourde pour plus de stabilité.',
    choices: [
      { id: 'a', label: 'Une lampe de bureau', isCorrect: true },
      { id: 'b', label: 'Un lustre en cristal', isCorrect: false },
      { id: 'c', label: 'Une applique murale', isCorrect: false },
    ],
  },
  {
    id: 'b-q18',
    mediaType: 'image',
    imageSrc: `${BASE}/q18/q18-disque-vinyle.png`,
    question: 'Quel format musical noir et rond était le roi incontesté avant l\'arrivée des cassettes ?',
    source: 'Souvenir du quotidien',
    caption: 'Disque vinyle 33 tours',
    hint: 'Il fallait le placer délicatement sur le plateau tournant avec un bras de lecture.',
    choices: [
      { id: 'a', label: 'Le disque vinyle 33 tours', isCorrect: true },
      { id: 'b', label: 'Le 45 tours', isCorrect: false },
      { id: 'c', label: 'Le microsillon', isCorrect: false },
    ],
  },
  {
    id: 'b-q19',
    mediaType: 'image',
    imageSrc: `${BASE}/q19/q19-chaise-cuisine.png`,
    question: 'Quel meuble de cuisine aux pieds chromés était présent dans presque tous les foyers des années 70 ?',
    source: 'Souvenir du quotidien',
    caption: 'Chaise de cuisine vintage',
    hint: 'Son assise était souvent en formica ou en skaï de couleur vive.',
    choices: [
      { id: 'a', label: 'Une chaise de cuisine en formica', isCorrect: true },
      { id: 'b', label: 'Un tabouret de bar', isCorrect: false },
      { id: 'c', label: 'Un fauteuil club', isCorrect: false },
    ],
  },
  {
    id: 'b-q20',
    mediaType: 'image',
    imageSrc: `${BASE}/q20/q20-horloge-murale.png`,
    question: 'Quel objet rond et coloré indiquait l\'heure dans les cuisines des années 70 avec son design rétro ?',
    source: 'Souvenir du quotidien',
    caption: 'Horloge murale vintage',
    hint: 'Elle était souvent en plastique avec des chiffres en relief ou des symboles.',
    choices: [
      { id: 'a', label: 'Une horloge murale vintage', isCorrect: true },
      { id: 'b', label: 'Un coucou suisse', isCorrect: false },
      { id: 'c', label: 'Une pendule de cheminée', isCorrect: false },
    ],
  },
];
