import { GameBQuestionDto } from '../../../models/session.model';

const BASE = 'assets/games/game-b/questions';

export const GAME_B_QUESTIONS: GameBQuestionDto[] = [
  {
    id: 'b-q1',
    mediaType: 'image',
    imageSrc: `${BASE}/q01/TGV-orange.png`,
    question: 'Quel est ce célèbre train rapide orange qui a révolutionné les voyages en France dès 1981 ?',
    source: 'Souvenir du quotidien',
    caption: 'Train grande vitesse',
    hint: 'Il reliait Paris à Lyon en moins de 3 heures et portait trois lettres.',
    choices: [
      { id: 'a', label: 'Le TGV', isCorrect: true },
      { id: 'b', label: 'Le Corail', isCorrect: false },
      { id: 'c', label: "L'Orient Express", isCorrect: false },
    ],
  },
  {
    id: 'b-q2',
    mediaType: 'image',
    imageSrc: `${BASE}/q02/Minitel.png`,
    question: 'Quel est le nom de ce petit terminal que France Télécom installait gratuitement chez les abonnés dans les années 80 ?',
    source: 'Souvenir du quotidien',
    caption: 'Terminal électronique',
    hint: "On l'utilisait pour consulter l'annuaire et commander des billets de train.",
    choices: [
      { id: 'a', label: 'Le Minitel', isCorrect: true },
      { id: 'b', label: 'Le Télétel', isCorrect: false },
      { id: 'c', label: "L'Antiope", isCorrect: false },
    ],
  },
  {
    id: 'b-q3',
    mediaType: 'image',
    imageSrc: `${BASE}/q03/Vintage_pro_Tv.png`,
    question: 'Comment appelait-on ce téléviseur avec ses grosses molettes de réglage et son antenne sur le dessus ?',
    source: 'Souvenir du quotidien',
    caption: 'Téléviseur vintage',
    hint: 'On réglait la luminosité et le contraste avec de grandes molettes sur le côté.',
    choices: [
      { id: 'a', label: 'Un téléviseur à tube cathodique', isCorrect: true },
      { id: 'b', label: 'Un magnétoscope', isCorrect: false },
      { id: 'c', label: 'Un rétroprojecteur', isCorrect: false },
    ],
  },
  {
    id: 'b-q4',
    mediaType: 'image',
    imageSrc: `${BASE}/q04/Plume.png`,
    question: 'Où versait-on l\'encre (souvent de marque Sergent-Major) pour écrire sur nos cahiers ?',
    source: 'Souvenir du quotidien',
    caption: 'Encre et plume',
    hint: "L'encre violette y était souvent versée par le maître.",
    choices: [
      { id: 'a', label: 'Dans un encrier encastré dans le bureau', isCorrect: true },
      { id: 'b', label: "Dans un tube de peinture à l'eau", isCorrect: false },
      { id: 'c', label: 'Dans un stylo à réservoir', isCorrect: false },
    ],
  },
  {
    id: 'b-q5',
    mediaType: 'audio',
    audioSrc: `${BASE}/q05/lhorloge-parlante.mp3`,
    question: 'Écoutez cet extrait. Quel était ce célèbre service téléphonique que l\'on appelait au 36 99 pour ne pas être en retard ?',
    source: 'Souvenir du quotidien',
    caption: 'Service téléphonique',
    hint: '"Au quatrième top, il sera exactement..."',
    choices: [
      { id: 'a', label: "L'horloge parlante", isCorrect: true },
      { id: 'b', label: 'Le réveil par téléphone', isCorrect: false },
      { id: 'c', label: 'Le répondeur de la Poste', isCorrect: false },
    ],
  },
  {
    id: 'b-q6',
    mediaType: 'image',
    imageSrc: `${BASE}/q06/Mange-disque.png`,
    question: 'Quel est le nom de cet appareil coloré, très populaire chez les jeunes dans les années 70 pour écouter des 45 tours ?',
    source: 'Souvenir du quotidien',
    caption: 'Lecteur de disques',
    hint: 'Son nom vient du fait qu\'il "avalait" le disque par une fente.',
    choices: [
      { id: 'a', label: 'Le Mange-disque', isCorrect: true },
      { id: 'b', label: 'Le Walkman (Baladeur)', isCorrect: false },
      { id: 'c', label: 'Le Jukebox portable', isCorrect: false },
    ],
  },
  {
    id: 'b-q7',
    mediaType: 'audio',
    audioSrc: `${BASE}/q07/Le-lund.mp3`,
    question: 'Écoutez cet extrait. Qui est ce célèbre chanteur, véritable idole des années 70, toujours accompagné de ses danseuses ?',
    source: 'Souvenir du quotidien',
    caption: 'Chanson des années 70',
    hint: 'On le surnommait affectueusement "Cloclo".',
    choices: [
      { id: 'a', label: 'Claude François', isCorrect: true },
      { id: 'b', label: 'Michel Polnareff', isCorrect: false },
      { id: 'c', label: 'Joe Dassin', isCorrect: false },
    ],
  },
  {
    id: 'b-q8',
    mediaType: 'image',
    imageSrc: `${BASE}/q08/portable-record-player.png`,
    question: 'Comment appelait-on ce tourne-disque portable en forme de valisette, souvent de marque Teppaz ?',
    source: 'Souvenir du quotidien',
    caption: 'Tourne-disque portable',
    hint: "C'était l'ancêtre de la chaîne hi-fi, qu'on emmenait dans les surprises-parties.",
    choices: [
      { id: 'a', label: 'Un électrophone portable', isCorrect: true },
      { id: 'b', label: 'Un gramophone à manivelle', isCorrect: false },
      { id: 'c', label: 'Un magnétophone à bandes', isCorrect: false },
    ],
  },
  {
    id: 'b-q9',
    mediaType: 'image',
    imageSrc: `${BASE}/q09/Socotel.png`,
    question: 'Comment composait-on un numéro avec ce téléphone emblématique des années 70, le modèle Socotel S63 ?',
    source: 'Souvenir du quotidien',
    caption: 'Téléphone à cadran',
    hint: 'Il fallait faire un mouvement circulaire puis relâcher.',
    choices: [
      { id: 'a', label: 'En tournant le cadran avec le doigt', isCorrect: true },
      { id: 'b', label: 'En appuyant sur de grosses touches', isCorrect: false },
      { id: 'c', label: 'En demandant à une opératrice', isCorrect: false },
    ],
  },
];
